MACRO_NEWS:
  1:
    keywords:
      - gdp
      - lạm phát
      - fdi
      - lãi suất
      - thị trường mở
      - omo
      - NHTW
      - ngân hàng trung ương
      - bơm tiền
      - chính sách tài khóa
    name:
      1st
  2:
    keywords:
      - xuất nhập khẩu
      - thặng dư
      - thâm hụt thương mại
      - chống bán phá giá
      - chuyển giá
    name:
      2nd
  3:
    keywords:
      - quy định
      - luật mới
      - dự thảo
      - nghị định
    name:
      3rd
  4:
    keywords:
      - đề xuất
      - bộ ngành
      - ngành
    name:
      4th
  5:
    keywords:
      - nhận định
      - quan điểm
      - phát biểu
      - phỏng vấn
      - lãnh đạo cấp cao
      - thủ tướng
      - bộ trưởng
    name:
      5th


INTERNATIONAL_NEWS:
  1:
    keywords:
      - mỹ 
      - FED
      - lãi suất
      - NHTW Châu âu
      - EU
      - ngân hàng trung ương châu âu
    name:
      1st
  2:
    keywords:
      - tỷ lệ thất nghiệp mỹ 
      - tỷ lệ thất nghiệp trung quốc
      - tỷ lệ thất nghiệp anh
      - tỷ lệ thất nghiệp nhật bản
      - tỷ lệ thất nghiệp khu vực châu âu
      - tỷ lệ thất nghiệp
      - anh
      - mỹ
      - trung quốc
      - nhật bản
      - khu vực châu âu
    name:
      2nd
  3:
    keywords:
      - chứng khoán mỹ
      - châu á
      - Dow jones
      - Nasdad
      - Hang Seng
      - Shanghai
      - Kospi
    name:
      3rd

  4:
    keywords:
      - Bloomberdg
      - WSJ
      - The Economist
    name:
      4th


VN_STOCK_MARKET:
  1:
    keywords:
      - STB
      - Ngân hàng Thương mại Cổ phần Sài Gòn Thương Tín
      - VCB
      - Ngân hàng TMCP Ngoại Thương Việt Nam
      - BID
      - Ngân hàng Thương mại Cổ phần Đầu tư và Phát triển Việt Nam
      - CTG
      - Ngân hàng Thương mại Cổ phần Công Thương Việt Nam
      - TCB
      - Techcombank
      - Ngân hàng TMCP Kỹ Thương Việt Nam
      - VPB
      - Ngân hàng TMCP Việt Nam Thịnh Vượng
      - MBB
      - Ngân hàng Thương mại Cổ phần Quân Đội
      - TPB
      - Ngân hàng Thương mại Cổ phần Tiên Phong
      - TPBank
      - HDB
      - HDBank
      - Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh
      - VNM
      - Công ty Cổ phần Sữa Việt Nam
      - Vinamilk
      - MSN
      - Công ty Cổ phần Tập đoàn MaSan
      - MaSan
      - SBT
      - Công ty Cổ phần Thành Thành Công - Biên Hòa
      - GAS
      - Tổng Công ty Khí Việt Nam - Công ty Cổ phần
      - POW
      - Tổng Công ty Điện lực Dầu khí Việt Nam - CTCP
      - PLX
      - Tập đoàn Xăng dầu Việt Nam
      - SSI
      - Công ty Cổ phần Chứng khoán SSI
      - VJC
      - Công ty Cổ phần Hàng không VietJet
      - vietjet
      - FPT
      - Công ty Cổ phần FPT
      - MWG
      - Công ty Cổ phần Đầu tư Thế Giới Di Động
      - PNJ
      - Công ty Cổ phần Vàng bạc Đá quý Phú Nhuận
      - REE
      - Công ty Cổ phần Cơ Điện Lạnh
      - HPG
      - Công ty Cổ phần Tập đoàn Hòa Phát
      - BVH
      - Tập đoàn Bảo Việt
      - KDH
      - Công ty Cổ phần Đầu tư và Kinh doanh Nhà Khang Điền
      - PDR
      - Công ty Cổ phần Phát triển Bất động sản Phát Đạt
      - NVL
      - Công ty Cổ phần Tập đoàn Đầu tư Địa ốc No Va
      - Novaland
      - TCH
      - Công ty Cổ phần Đầu tư Dịch vụ Tài chính Hoàng Huy
      - VRE
      - Công ty Cổ phần Vincom Retail
      - Vincom Retail
      - VHM
      - Công ty Cổ phần Vinhomes
      - Vinhomes
      - VIC
      - Tập đoàn Vingroup - Công ty Cổ phần
      - Vingroup
    name:
      1st
  2:
    keywords:
      - bản tin thị trường
      - giá cả thị trường
      - tin tức về thị trường
      - diễn biến thị trường
      - biến động thị trường
      - mua ròng
      - mua bán ròng
      - bán ròng
    name:
      2nd
  3:
    keywords:
      - tự doanh
      - tự doanh CTCK
    name:
      3rd

BANKING:
  1:
    keywords:
      - STB
      - Ngân hàng Thương mại Cổ phần Sài Gòn Thương Tín
      - VCB
      - Ngân hàng TMCP Ngoại Thương Việt Nam
      - BID
      - Ngân hàng Thương mại Cổ phần Đầu tư và Phát triển Việt Nam
      - CTG
      - Ngân hàng Thương mại Cổ phần Công Thương Việt Nam
      - TCB
      - Techcombank
      - Ngân hàng TMCP Kỹ Thương Việt Nam
      - VPB
      - Ngân hàng TMCP Việt Nam Thịnh Vượng
      - MBB
      - Ngân hàng Thương mại Cổ phần Quân Đội
      - TPB
      - TPBank
      - Ngân hàng Thương mại Cổ phần Tiên Phong
      - HDB
      - HDBank
      - Ngân hàng TMCP Phát triển Thành phố Hồ Chí Minh
    name:
      1st

  2:
    keywords:
      - chính sách tài khóa
      - ngân hàng nhà nước
      - NHTW
      - ngân hàng trung ương
      - lãi suất
      - chính sách vĩ mô
      - quyết định hội đồng thường niên
      - quyết định của đại hội đồng thường niên
      - quyết định của hội đồng thường niên
      - trích lập lợi nhuận
      - lãi suất huy động
      - quyết định của HĐQT
      - quyết định HĐQT
      - quyết định của hội đồng quản trị
      - quyết định hội đồng quản trị
      - quyết định vĩ mô
      - quyết định vĩ mô của ngân hàng nhà nước
      - quyết định vĩ mô của NHNN
      - lạm phát
      - Basel I
      - Basel II
      - Basel III
      - Basel 1
      - Basel 2
      - Basel 3
      - trái phiếu
      - tham nhũng
      - tham nhũng ngân hàng
      - tham ô
    name:
      2nd

REAL_ESTATE:
  1:
    keywords:
      - KDH
      - Công ty Cổ phần Đầu tư và Kinh doanh Nhà Khang Điền
      - PDR
      - Công ty Cổ phần Phát triển Bất động sản Phát Đạt
      - NVL
      - Công ty Cổ phần Tập đoàn Đầu tư Địa ốc No Va
      - Novaland
      - TCH
      - Công ty Cổ phần Đầu tư Dịch vụ Tài chính Hoàng Huy
    name:
      1st
  2:
    keywords:
      - BĐS
      - bất động sản
      - bộ xây dựng
      - đất công
      - dự án
      - thu hồi
      - giải phóng mặt bằng
      - đấu giá
      - quy hoạch
      - địa ốc
      - thủ tục pháp lý
      - giá đất
      - quyết định của UBND
    name:
      2nd

OIL_AND_GAS:
  1:
    keywords:
      - GAS
      - Tổng Công ty Khí Việt Nam - Công ty Cổ phần
      - POW
      - Tổng Công ty Điện lực Dầu khí Việt Nam - CTCP
      - PLX
      - Tập đoàn Xăng dầu Việt Nam
    name:
      1st
  2:
    keywords:
      - nhu cầu điện
      - giá dầu
      - khí gas
      - giá xăng
      - LNG
      - phát triển điện khí
      - hợp đồng mới
      - thay đổi môi trường kinh doanh
      - opec+
      - opec +
      - opec
      - thương mại hoa kỳ - trung quốc
      - tồn kho dầu ở hoa kỳ
      - năng lượng sạch
    name:
      2nd

VINGROUP:
  1:
    keywords:
      - VRE
      - Công ty Cổ phần Vincom Retail
      - Vincom Retail
      - VHM
      - Công ty Cổ phần Vinhomes
      - Vinhomes
      - VIC
      - Tập đoàn Vingroup - Công ty Cổ phần
      - Vingroup
    name:
      1st
  2:
    keywords:
      - xe điện
      - giá nhà đất
      - trung tâm thương mại
    name:
      2nd

FOOD_AND_DRINK:
  1:
    keywords:
      - VNM
      - Công ty Cổ phần Sữa Việt Nam
      - Vinamilk
      - MSN
      - Công ty Cổ phần Tập đoàn MaSan
      - MaSan
      - SBT
      - Công ty Cổ phần Thành Thành Công - Biên Hòa
    name:
      1st
  2:
    keywords:
      - sữa
      - GTN Foods
      - Mộc châu Milk
      - sữa mộc châu
      - vonfram
      - mía đường
      - giá thịt
      - giá thịt lợn
    name:
      2nd

OTHERS:
  1:
    keywords:
      - SSI
      - Công ty Cổ phần Chứng khoán SSI
      - VJC
      - Công ty Cổ phần Hàng không VietJet
      - vietjet
      - FPT
      - Công ty Cổ phần FPT
      - MWG
      - Công ty Cổ phần Đầu tư Thế Giới Di Động
      - PNJ
      - Công ty Cổ phần Vàng bạc Đá quý Phú Nhuận
      - REE
      - Công ty Cổ phần Cơ Điện Lạnh
      - HPG
      - Công ty Cổ phần Tập đoàn Hòa Phát
      - BVH
      - Tập đoàn Bảo Việt
    name:
      1st
  2:
    keywords:
      - giá thép
      - sản lượng thép
      - thuế chống bán phá giá
      - HRC
      - thép cán nóng
      - ống thép
      - hàng không
      - thị trường tài chính
    name:
      2nd